### ISSUE TITLE
Adding MathJax increases first element's top margin (Github themes)

### ISSUE THREAD

**Issue by ze-phyr-us** [uranusjr/macdown#305]
It seems that when MathJax is enabled, this selector in GitHub2 (and a similar one in GitHub) stop working:

```css
body > *:first-child {
  margin-top: 0 !important; }
```

So the first heading of the document ends up with excess top margin. I'm guessing this is because MathJax script tags are being injected right after `<body>` before the actual document. Perhaps it can be loaded in the `<head>` instead?

**Comment by dpvc** [comment]
It's not the script tag, it's the fact that MathJax inserts hidden DIVs into the page for things like its message box, and some boxes for measuring the sizes of elements during layout.

**Comment by ze-phyr-us** [comment]
I see. In that case the themes could be fixed by using `:first-of-type` selectors:

```css
body > h1:first-of-type, body > p:first-of-type {
  margin-top: 0 !important; }
```

(All h* tags, lists, blockquotes etc.would need to be added.)

Another option would be to put the rendered document inside another tag and not directly in `<body>`. Perhaps `<main>`. Then the theme CSS could be changed to 

```css
main > *:first-child {
  margin-top: 0 !important; }
```
